version: "3.8"
services:
    mysql:
        image: "mysql:8.0"
        environment:
            - MYSQL_DATABASE=mydatabase
            - MYSQL_ROOT_PASSWORD=verysecret
        # Removed public port exposure
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - db_data:/var/lib/mysql
        expose:
            - "3306:3306" # Expose MySQL port to other services in the same network

    api:
        build:
            context: ./apps/api
            dockerfile: Dockerfile
            args:
                - DB_URL=jdbc:mysql://mysql:3306/mydatabase
                - DB_USERNAME=root
                - DB_PASSWORD=verysecret
                - DOCKER_COMPOSE_ENABLED=false
        environment:
            - DB_URL=jdbc:mysql://mysql:3306/mydatabase
            - DB_USERNAME=root
            - DB_PASSWORD=verysecret
            - DOCKER_COMPOSE_ENABLED=false
        depends_on:
            mysql:
                condition: service_healthy
        ports:
            - "8080:8080"

    web:
        build:
            context: ./apps/web
            dockerfile: Dockerfile
        depends_on:
            - api
        ports:
            - "4200:4200"
        environment:
            - NODE_ENV=development
            - API_URL=http://api:8080/api

volumes:
    db_data: