version: "3.8"
services:
    mysql:
        image: "mysql:8.0"
        environment:
            - MYSQL_DATABASE=mydatabase
            - MYSQL_ROOT_PASSWORD=verysecret
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - db_data:/var/lib/mysql
        expose:
          - "3306:3306"

    api:
        build:
            context: ./apps/api
            dockerfile: Dockerfile.prod
            args:
                - DB_URL=jdbc:mysql://mysql:3306/mydatabase
                - DB_USERNAME=root
                - DB_PASSWORD=verysecret
                - DOCKER_COMPOSE_ENABLED=false
        environment:
            - DB_URL=jdbc:mysql://mysql:3306/mydatabase
            - DB_USERNAME=root
            - DB_PASSWORD=verysecret
            - DOCKER_COMPOSE_ENABLED=false
        depends_on:
            mysql:
                condition: service_healthy
        ports:
            - "8080:8080"

    web:
        build:
            context: ./apps/web
            dockerfile: Dockerfile.prod
        depends_on:
            - api
        ports:
            - "4200:4000"
        env_file:
            - ../../.env.prod

volumes:
    db_data:
